### ISSUE TITLE
direct hyperlink for my address

### ISSUE THREAD

**Issue by gvian** [CoinBlack/blackcoinmore.org#7]
for example, [my bitcoin address](https://btc.com/3K7Ba2DFyyuGTukNqXEmogG4VgYp2RWnZV)

for my blackcoin address `B4pCYCRhS6itEs2rsSAVbRnoKkL6thj3Bt`, how?

**Comment by jschaeke** [comment]
Enter your address in a Blackcoin explorer e.g. https://bitinfocharts.com/blackcoin/
